index:
    path: /
    controller: App\Controller\DefaultController::index

page_by_category:
    path: /category/{categoryName}
    controller: App\Controller\CategoryController::showPageByCategory

contacts_page:
    path: /contacts
    controller: App\Controller\ContactsController::showContacts